Feature/OIDC
maykinmedia/referentielijsten pull request #7
Opened 2024-05-14 05:05 UTC by bart-maykin

fixes #3

2024-05-17 10:19 UTC, stevenbal requested changes
Currently logging in with OIDC doesn't work, because the following line is missing from the `AUTHENTICATION_BACKENDS`:

```python
"mozilla_django_oidc_db.backends.OIDCAuthenticationBackend",
```

Please make sure to test it locally if it works, in the repo of `mozilla-django-oidc-db` there is a docker compose setup you can use to run Keycloak as an identity provider: https://github.com/maykinmedia/mozilla-django-oidc-db/tree/master/docker

If you get that container running and set the following settings in the Referentielijsten admin (OIDC config), it should be possible to test this locally:

![image](https://github.com/maykinmedia/referentielijsten/assets/29249171/20c776d1-7b0c-453d-8ca3-6c00d98921ef)

2024-05-17 10:19 UTC, stevenbal commented on src/referentielijsten/conf/base.py
> +MOZILLA_DJANGO_OIDC_DB_CACHE = "oidc"
Can you add the following line here as well:

```python
OIDC_CALLBACK_CLASS = "mozilla_django_oidc_db.views.OIDCCallbackView"
```

This way we can properly catch errors and display them if they occur

2024-05-17 10:19 UTC, stevenbal commented on src/referentielijsten/urls.py
> +    path("oidc/", include("mozilla_django_oidc.urls")),
Please also add this line to add the error view:

```python
path("login/failure/", AdminLoginFailure.as_view(), name="admin-oidc-error"),
```

2024-05-17 10:19 UTC, stevenbal commented on src/referentielijsten/conf/base.py
> +            "handlers": ["project"],
Let's make logging to console possible
```suggestion
            "handlers": ["project"] if not LOG_STDOUT else ["console"],
```

2024-05-17 10:19 UTC, stevenbal commented on src/referentielijsten/accounts/tests/test_oidc.py
> +        )
Once you've added the admin failure view, can you also add a test for the error flow and the happy flow? OF has these tests as well: https://github.com/open-formulieren/open-forms/blob/master/src/openforms/accounts/tests/test_oidc.py

2024-05-17 10:20 UTC, stevenbal commented
Also I see that the tests in CI seem to be skipped, so there's probably something going wrong in the GH actions setup? 

![image](https://github.com/maykinmedia/referentielijsten/assets/29249171/7b64c695-af22-4151-9fc5-0f254ed46da9)

2024-05-17 14:23 UTC, Coperh approved these changes
Other than the things Steven caught (which I probably would not have), looks good.

Appears on the login page and styling works.

2024-05-30 08:58 UTC, stevenbal approved these changes

2024-05-30 08:58 UTC, merged